### PR TITLE
Fake a commit and fixed a typo

### PR DESCRIPTION
**Pull request by JeffInChrist**
We need to fake a commit to fix the display name of [bhpappir (SaiBhavya PappiReddy) (github.com)](https://github.com/bhpappir).

The issue is logged in https://ceapex.visualstudio.com/Engineering/_workitems/edit/979990

**Reminder**: this PR should **NOT** be merged in squash mode.

### CODE REVIEW

**Comment by mtrilbybassett** [comment]
@Prithvi-MSFT could you please review and merge this PR? It addresses a display error in the commit history. 

Also, do **NOT** merge in squash mode.

**Comment by mtrilbybassett** [comment]
@Jegadeesh-MSFT could you please review and merge this PR? It addresses a display error in the commit history.

Also, do **NOT** merge in squash mode.

**Comment by mtrilbybassett** [comment]
@Mohammed-MSFT could you please review and merge this PR? It addresses a display error in the commit history.

Also, do NOT merge in squash mode.

**Review by mtrilbybassett — APPROVED** [review]

**Comment by mtrilbybassett** [comment]
@Harikrishnan-MSFT could you please review and merge this PR? It addresses a display error in the commit history.

Also, do NOT merge in squash mode.

**Comment by mtrilbybassett** [comment]
@Wajeed-msft could you please review and merge this PR? It addresses a display error in the commit history.

Also, do NOT merge in squash mode.

**Comment by JeffInChrist** [comment]
@Prithvi-MSFT ,@Jegadeesh-MSFT ,@Mohammed-MSFT ,@Harikrishnan-MSFT ,@Wajeed-msft could anyone of you please review and merge this PR? 

It addresses a display error in the commit history. On [Learn page](https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-meetings-share-to-stage-signing-csharp/), it displays the email rather than user name of SaiBhavya PappiReddy. This PR is intend to replace the email address with the user name of SaiBhavya PappiReddy.
image

Also, do NOT merge in squash mode. Thanks :)

**Pull request merged**
