### PR TITLE
bot-sso quickstart sample fixes

### PR DESCRIPTION
**Pull request by Prithvi-MSFT**

### CODE REVIEW

**Review by Pawan-MSFT — APPROVED** [review]
Looks correct, Approving it.

**Review by Pawan-MSFT — COMMENTED** [review]
run build pipeline before merge

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving the PR.

**Comment by Prithvi-MSFT** [comment]
Build pipeline - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/4170804492

**Review by Wajeed-msft — APPROVED** [review]

**Pull request merged**
