### PR TITLE
Fixed tab request approval issue

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**

### CODE REVIEW

**Comment by Harikrishnan-MSFT** [comment]
Build Pipeline - 
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/4858202016

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Review by Mohammed-MSFT — APPROVED** [review]
Changes Looks fine, Approving this PR.

**Comment by ChetanSharma-msft** [comment]
@Harikrishnan-MSFT - Run build pipeline

**Comment by Harikrishnan-MSFT** [comment]
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5077072081

image

**Comment by Harikrishnan-MSFT** [comment]
> @Harikrishnan-MSFT - Run build pipeline

**Review by Wajeed-msft — APPROVED** [review]

**Pull request merged**
