### PR TITLE
Update README.md for #737

### LINKED ISSUE #737: Request to update bot-calling-meeting tutorial
Hi, I recently followed this tutorial: [Calling and Meeting Bot Sample V4](https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-bot-calling-meeting-csharp/). And I want to make some fix to it.

1. Typo: the `Get-CsApplicationAccessPolicy -PolicyName Meeting-policy-dev -Identity "<<microsoft-app-id>>"` should actually be `Get-CsApplicationAccessPolicy -Identity Meeting-policy-dev`, according to docs of [Get-CsApplicationAccessPolicy](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md)
2. I'd like to add a short part for `pwsh` for mac developers, like installing powershell and its modules with homebrew / dotnet. For example <https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-install>
3. folder `TeamsAppManifest` should be `Manifest`(?)
That's all so far. Should I make a PR?

### PR DESCRIPTION
**Pull request by PabloLION**
this PR resolves #737 in three major aspects
1. update arguments of CLI [Get-CsApplicationAccessPolicy](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md)
2. add a link for mac PowerShell installation. And split the installation of "Microsoft Teams PowerShell Module" from using this module.
3. correct `TeamsAppManifest` folder to `Manifest`

I hope this should meet your standards. @sayali-MSFT @ChetanSharma-msft

### CODE REVIEW

**Comment by PabloLION** [comment]
@microsoft-github-policy-service agree

**Comment by Prithvi-MSFT** [comment]
@PabloLION  - Could you please change the manifest folder name to AppManifest, as same structure is followed in other samples

**Comment by PabloLION** [comment]
@Prithvi-MSFT Do you mean something like the last commit I just made?

**Comment by PabloLION** [comment]
I rebased the commit onto the latest `main` branch with 2 conflict on `png` files due to renaming the `Manifest` folder.

**Comment by PabloLION** [comment]
I think this PR is containing too many commits now and it's not very readable. Maybe I should close this one and create a new PR?

**Comment by Prithvi-MSFT** [comment]
Yes that would be a good option

**Comment by PabloLION** [comment]
@Prithvi-MSFT I made a new PR #1027 , could you have a look at it? It's the same thing with "4. I also made a markdown-lint of the README file. If you don't like it, feel free to revert the last change."

**Pull request closed without merging**
