### PR TITLE
msgext-action-preview sample UI fixes.

### PR DESCRIPTION
**Pull request by ChetanSharma-msft**

### CODE REVIEW

**Comment by ChetanSharma-msft** [comment]
Raised one bug as well: https://github.com/microsoft/botbuilder-js/issues/4616

**Review by Pawank-MSFT — APPROVED** [review]
looks correct, Approving!

**Comment by Pawank-MSFT** [comment]
executed build pipeline
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/7884009624

**Review by Prithvi-MSFT — APPROVED** [review]
approved

**Pull request merged**
