### PR TITLE
Migration to net6.0, readme, build pipeline changes

### PR DESCRIPTION
**Pull request by ChetanSharma-msft**

### CODE REVIEW

**Review by Pawan-MSFT — APPROVED** [review]
Changes looks correct, approving.

**Review by Wajeed-msft — APPROVED** [review]
Please make sure the Build pipeline is successful after the check in.

**Comment by ChetanSharma-msft** [comment]
Yes, sure.
We will merge the changes and if pipeline is failing, we will fix those.

**Comment by ChetanSharma-msft** [comment]
**Executed build pipeline:** 
**Result:**

**Comment by ChetanSharma-msft** [comment]
**Executed build pipeline again:** https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3614102772
Result:

**Pull request merged**
