### PR TITLE
Updating node sample dependencies

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**

### CODE REVIEW

**Review by Pawan-MSFT — APPROVED** [review]
looks correct approving

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Review by Wajeed-msft — APPROVED** [review]

**Comment by ChetanSharma-msft** [comment]
Executed build pipeline:

**Comment by ChetanSharma-msft** [comment]
Build pipeline is failing, so once it is fixed, we will merge this PR.

**Comment by Pawan-MSFT** [comment]
Execute build pipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3820561558

Result:
image

**Pull request merged**
