### PR TITLE
App Icon Badging Toolkit Fixes HealthCheck

### PR DESCRIPTION
**Pull request by Mohammed-MSFT**

### CODE REVIEW

**Review by Pawank-MSFT — APPROVED** [review]
looks correct, Approving!

**Comment by Pawank-MSFT** [comment]
Executed Build pipeline: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/7883807573

**Review by Prithvi-MSFT — APPROVED** [review]
approved

**Comment by Pawank-MSFT** [comment]
Executed buildpipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/7899363802

**Pull request merged**
