### PR TITLE
Tab-Support-Offline Node.js TTK Sample

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**

### CODE REVIEW

**Comment by Harikrishnan-MSFT** [comment]
**Build Pipeline -** 
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/10684994473

**Review by cpjoshi — APPROVED** [review]
approved.

**Review by Jegadeesh-MSFT — APPROVED** [review]
Looks correct !

**Comment by Harikrishnan-MSFT** [comment]
Build Pipeline - 

https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/10766743477

image

**Pull request merged**
