### PR TITLE
Updating TeamsAppManifest to AppManifest

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**

### CODE REVIEW

**Comment by Harikrishnan-MSFT** [comment]
**Build Pipeline -** 
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6064204266

**Comment by Harikrishnan-MSFT** [comment]
**Build Pipeline -**
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6081440483
image

**Review by ChetanSharma-msft — APPROVED** [review]
Looks fine, approving it.

**Comment by ChetanSharma-msft** [comment]
@Harikrishnan-MSFT - Please run build pipeline.

**Comment by ChetanSharma-msft** [comment]
Executed build pipeline: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6156767646

**Review by Prithvi-MSFT — APPROVED** [review]

**Pull request merged**
