### PR TITLE
Adaptive Card responsive layout(C# and NodeJS)

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**

### CODE REVIEW

**Review by Pawank-MSFT — APPROVED** [review]
looks correct, Approved!

**Review by robin-liao — APPROVED** [review]

**Comment by Harikrishnan-MSFT** [comment]
image

**Review by Prithvi-MSFT — APPROVED** [review]

**Review by Prithvi-MSFT — APPROVED** [review]

**Comment by Pawank-MSFT** [comment]
Executed Buildpipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/8360704348

**Comment by Pawank-MSFT** [comment]
Executed build pipeline :
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/8360704348

**Pull request merged**
