### PR TITLE
PR 6 - Implement New toolkit version csharp samples

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**
Sample list - 

1. bot-configuration-app/csharp
2. bot-people-picker-adaptive-card
3. bot-teams-authentication
4. bot-type-ahead-search-adaptive-cards
5. bot-message-reaction

### CODE REVIEW

**Review by Alive-Fish — APPROVED** [review]
Look good to me. Merge it before testing the samples.

**Comment by Harikrishnan-MSFT** [comment]
Build Pipeline - 
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/9253463265
image

**Review by Mohammed-MSFT — APPROVED** [review]
Looks good, Approved.

**Review by Mohammed-MSFT — APPROVED** [review]

**Review by Pawank-MSFT — APPROVED** [review]
looks correct, Approving!

**Pull request merged**
