### PR TITLE
update  MainReadme and Manifest

### PR DESCRIPTION
**Pull request by Keshav-MSFT**

### CODE REVIEW

**Review by Pawan-MSFT — COMMENTED** [review]
for Meeting-stage-view package.json missing.

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Comment by ChetanSharma-msft** [comment]
@Keshav-MSFT - Kindly run build pipeline for this.

**Review by Pawan-MSFT — APPROVED** [review]
looks correct, Approving

**Comment by ChetanSharma-msft** [comment]
Execute build pipeline:

**Pull request merged**
