### PR TITLE
Updating root readme with toolkit icon

### PR DESCRIPTION
**Pull request by Jegadeesh-MSFT**

### CODE REVIEW

**Comment by Jegadeesh-MSFT** [comment]
**Executed Build Pipeline**
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6222631724
image

**Review by ChetanSharma-msft — APPROVED** [review]
looks fine

**Review by Pawank-MSFT — COMMENTED** [review]
Please resolve the conflict,

**Review by Pawank-MSFT — APPROVED** [review]
look ok , Approving!

**Pull request merged**
