### PR TITLE
PR 7 - Implement New toolkit version csharp samples

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**
Sample List - 

1. msgext-action-preview
2. bot-sso-adaptivecard
3. msgext-action
4. bot-join-team-using-qr-code
5. bot-receive-channel-messages-withRSC

### CODE REVIEW

**Review by Alive-Fish — APPROVED** [review]
Look good to me. Merge it before testing the samples.

**Comment by Harikrishnan-MSFT** [comment]
Build Pipeline - 
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/9253458588
image

**Review by Mohammed-MSFT — APPROVED** [review]
looks correct approving...

**Review by Pawank-MSFT — APPROVED** [review]
Looks correct, Approving!

**Pull request merged**
