### PR TITLE
Adding demo manifest

### PR DESCRIPTION
**Pull request by Harikrishnan-MSFT**

### CODE REVIEW

**Review by Pawan-MSFT — APPROVED** [review]
looks correct, approving!

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Comment by ChetanSharma-msft** [comment]
Approved it but please update yml build and deployment file for these newly added demo manifests and also link it with Microsoft documentation and our root readme files.

**Comment by Harikrishnan-MSFT** [comment]
Build Pipeline - 
image

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Pull request merged**
