### PR TITLE
Meetings Sidepanel Bug Fixes

### PR DESCRIPTION
**Pull request by Mohammed-MSFT**
[SidePanel Sample Not Loading .env · Issue #951 · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/951) **(Fixed)**

[SidePanel Sample ClientApp Fails with Node 18 · Issue #953 · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/953) **(Fixed)**

### CODE REVIEW

**Review by Prithvi-MSFT — APPROVED** [review]
approved

**Review by Pawank-MSFT — APPROVED** [review]
looks correct, Approving!

**Comment by Pawank-MSFT** [comment]
Executed build pipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6766624013

**Comment by Mohammed-MSFT** [comment]
build Pipeline Executed Succefully
image

**Pull request merged**
