### PR TITLE
Added Missing Modules/Fixes

### PR DESCRIPTION
**Pull request by Mohammed-MSFT**
1. Updated Application URL  Port to **5000** in Properties/launchsettings.json for **App Hello world** Chsarp Sample but not showing on git changes.
2. Added Missing Module in package.json for Meeting Sidepanel Sample Csharp

### CODE REVIEW

**Review by ChetanSharma-msft — APPROVED** [review]
Looks fine

**Comment by ChetanSharma-msft** [comment]
Mohammed Furquan- 
Kindly push these changes:

**Comment by ChetanSharma-msft** [comment]
Mohammed Furquan- 
Kindly push these changes:

image

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Review by Jegadeesh-MSFT — APPROVED** [review]
changes look fine.

**Comment by ChetanSharma-msft** [comment]
Executed build pipeline: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6176411009

**Pull request merged**
