### PR TITLE
Added fixes for graph broadcast csharp sample

### PR DESCRIPTION
**Pull request by Prithvi-MSFT**

### CODE REVIEW

**Review by ChetanSharma-msft — APPROVED** [review]
Looks fine

**Comment by ChetanSharma-msft** [comment]
@Prithvi-MSFT - Kindly run build pipeline.

**Review by Pawank-MSFT — APPROVED** [review]
looks fine, Approving!

**Comment by Pawank-MSFT** [comment]
Run Build pipeline and merge this.

**Comment by Prithvi-MSFT** [comment]
Build status - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6295345550

**Comment by ChetanSharma-msft** [comment]
Executed build pipeline: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6298484186

**Comment by ChetanSharma-msft** [comment]
image

**Pull request merged**
