### PR TITLE
Added deployment fixes for tab-device-permission sample

### PR DESCRIPTION
**Pull request by Prithvi-MSFT**

### CODE REVIEW

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Review by Harikrishnan-MSFT — APPROVED** [review]

**Comment by ChetanSharma-msft** [comment]
@Prithvi-MSFT - Executed build pipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5996034853

**Comment by ChetanSharma-msft** [comment]
Executed again: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5996290763

**Comment by ChetanSharma-msft** [comment]
Build pipeline executed successfully:
image

**Pull request merged**
