### PR TITLE
Demo manifest missing entries and corrected folder structure

### PR DESCRIPTION
**Pull request by Prithvi-MSFT**

### CODE REVIEW

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Review by ChetanSharma-msft — CHANGES_REQUESTED** [review]
Please check build and deployment pipeline path and update those as well.

**Review by ChetanSharma-msft — CHANGES_REQUESTED** [review]
Run pipeline as well.

**Review by ChetanSharma-msft — CHANGES_REQUESTED** [review]
verify the Microsoft document for sample links and manifest.

**Comment by Prithvi-MSFT** [comment]
Build status - All builds passed.
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/4160365853

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Pull request merged**
