### PR TITLE
Updated Package.Json file to fix compilation issues (Meeting-live-code-interview)

### PR DESCRIPTION
**Pull request by Mohammed-MSFT**
Issue link : [Local debug meeting live code interview nodejs version failed](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1486) 

**Sample fixed and working screenshots**
**Nodejs v - 18.17.1**
image
**Added (Testing Code) at line No.7 and got notified**
image

### CODE REVIEW

**Comment by ChetanSharma-msft** [comment]
@Mohammed-MSFT - Please check and merge this PR as soon as possible.

**Review by ChetanSharma-msft — APPROVED** [review]
Looks fine.

**Review by Harikrishnan-MSFT — APPROVED** [review]
Looks good approved..

**Comment by Mohammed-MSFT** [comment]
**Executed Build Pipeline :** https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/12562354308
image

**Pull request merged**
